language: go

go:
  - 1.7.1
  - tip

install:
  - go get github.com/segmentio/analytics-go
  - go get github.com/sendgrid/sendgrid-go
  - go get github.com/smartystreets/goconvey
  - go get github.com/koding/metrics

matrix:
  allow_failures:
    - go: tip
